{"tags":["c#","исключения","com"],"owner":{"reputation":159,"user_id":264701,"user_type":"registered","accept_rate":75,"profile_image":"https://i.stack.imgur.com/wYTTQ.jpg?s=128&g=1","display_name":"Kellso","link":"https://ru.stackoverflow.com/users/264701/kellso"},"is_answered":true,"view_count":54,"accepted_answer_id":918847,"answer_count":1,"score":1,"last_activity_date":1544593267,"creation_date":1544546310,"last_edit_date":1544593267,"question_id":918656,"link":"https://ru.stackoverflow.com/questions/918656/%d0%9a%d0%b0%d0%ba-%d0%b2%d1%8b%d0%b7%d0%b2%d0%b0%d1%82%d1%8c-%d0%be%d1%88%d0%b8%d0%b1%d0%ba%d1%83-%d0%bf%d0%be%d0%bd%d1%8f%d1%82%d0%bd%d1%83%d1%8e-%d0%b4%d0%bb%d1%8f-com","title":"Как вызвать ошибку понятную для COM?","body":"<p>Как реализовать вызов ошибки, как com-объект?</p>\n\n<p>Сейчас из JavaScript кода, создается:</p>\n\n<pre><code>var customObject = new ActiveXObject(\"NAMESPACE.CLASS_NAME\");\ncustomObject.GETWRAPPER.CallMethodHttpCom(\"METHOD_NAME\");\n</code></pre>\n\n<p>Так вызывается C# метод. Из этого метода вылетает ошибка с каким-то сообщением. Мне необходимо, что бы при перехвате try..catch(error) из JS, я смог увидеть это своё сообщение.</p>\n\n<p>Сейчас же я вижу:\n<a href=\"https://i.stack.imgur.com/QzC7c.png\" rel=\"nofollow noreferrer\"><img src=\"https://i.stack.imgur.com/QzC7c.png\" alt=\"Содержимое объекта error\"></a></p>\n\n<p>Т.е. не то сообщения что я вызывал в C#.</p>\n\n<p>Мне подсказали смотреть в сторону IUnknown, но к моему большому сожалению, не могу понять что я там должен увидеть.</p>\n\n<p>Подскажите как реализовать или где посмотреть примеры для подобных проблем?</p>\n"}